order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

imag_ldap:
  resource: "@IMAGLdapBundle/Resources/config/routing.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
